security:
    encoders:
        GR\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        admin_provider:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_login:
            pattern: ^/admin/login$
            anonymous: true
            provider: admin_provider

        admin:
            pattern: ^/admin
            anonymous: true
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: admin_provider
                csrf_token_generator: security.csrf.token_manager
                default_target_path: gr_admin_dashboard
                remember_me: true
            remember_me:
                secret: '%secret%'
            logout:
                path: fos_user_security_logout
                target: /
        main:
            pattern: ^/
            anonymous: true
        
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    
