security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        GR\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        admin_provider:
            entity:
                class: GR\UserBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_login:
            pattern: ^/admin/login$
            anonymous: true
            provider: admin_provider
        admin:
            pattern: ^/admin
            anonymous: false
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: gr_admin_dashboard
            logout:
                path: logout
                target: gr_showcase_homepage
        main:
            pattern: ^/
            anonymous: true
        
    access_control:
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
