<?php

namespace GR\AdminBundle\Repository;

/**
 * TownServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
